#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DraasGames.Core.Runtime.Infrastructure.Logger;
using UnityEditor;
using UnityEngine;

namespace Packages.DraasGames.Core.Editor
{
    /// <summary>
    /// Generates a static <c>DLogTags</c> class of <c>const string</c> tag names from the tag list in
    /// <see cref="DLoggerSettings"/>, so messages can be tagged in a compile-safe way:
    /// <c>DLogger.Log("msg", this, DLogTags.UI)</c>. Re-run after editing the tags in
    /// Project Settings &gt; DraasGames.
    /// </summary>
    internal static class DLogTagsGenerator
    {
        private const string ClassName = "DLogTags";
        private const string ReservedNoneTag = "None";

        [MenuItem("DraasGames/Logger/Generate Tags")]
        public static void GenerateFromSettings()
        {
            var settings = Resources.Load<DLoggerSettings>(DLoggerSettings.ResourcePath);
            if (settings == null)
            {
                Debug.LogError(
                    "[DLogTagsGenerator] DLoggerSettings asset not found. " +
                    "Open Project Settings > DraasGames to create it first.");
                return;
            }

            Generate(settings.Tags, settings.GeneratedTagsPath, settings.GeneratedTagsNamespace);
        }

        public static void Generate(IReadOnlyList<string> tags, string path, string @namespace)
        {
            if (string.IsNullOrEmpty(path))
            {
                Debug.LogError("[DLogTagsGenerator] Output path is empty. Set it in Project Settings > DraasGames.");
                return;
            }

            var pairs = BuildPairs(tags);
            var content = BuildSource(pairs, @namespace);

            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // Skip the write (and the recompile it triggers) when nothing changed.
            if (File.Exists(path) && File.ReadAllText(path) == content)
            {
                return;
            }

            File.WriteAllText(path, content);
            AssetDatabase.ImportAsset(path);
            AssetDatabase.Refresh();
            Debug.Log($"[DLogTagsGenerator] Generated {pairs.Count} tag(s) -> {path}");
        }

        private static List<KeyValuePair<string, string>> BuildPairs(IReadOnlyList<string> tags)
        {
            var pairs = new List<KeyValuePair<string, string>>();
            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            if (tags == null)
            {
                return pairs;
            }

            foreach (var tag in tags)
            {
                if (string.Equals(tag, ReservedNoneTag, StringComparison.OrdinalIgnoreCase))
                {
                    Debug.LogWarning(
                        "[DLogTagsGenerator] Skipping reserved tag name \"None\" — it is used by the " +
                        "DConsole \"untagged\" filter.");
                    continue;
                }

                var name = ToIdentifier(tag);
                if (name == null || !usedNames.Add(name))
                {
                    // Skip empty/invalid tags and ones that collapse to a duplicate identifier.
                    continue;
                }

                pairs.Add(new KeyValuePair<string, string>(name, tag));
            }

            return pairs;
        }

        private static string BuildSource(List<KeyValuePair<string, string>> pairs, string @namespace)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated by DLogTagsGenerator. Do not edit manually.");
            sb.AppendLine("//     Edit tags in Project Settings > DraasGames, then click \"Generate Tags\".");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using DraasGames.Core.Runtime.Infrastructure.Logger;");
            sb.AppendLine();

            var hasNamespace = !string.IsNullOrEmpty(@namespace);
            var indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                sb.Append("namespace ").AppendLine(@namespace);
                sb.AppendLine("{");
            }

            sb.Append(indent).Append("public static class ").AppendLine(ClassName);
            sb.Append(indent).AppendLine("{");

            foreach (var pair in pairs)
            {
                sb.Append(indent).Append("    public static readonly DLogTag ").Append(pair.Key)
                    .Append(" = new DLogTag(\"").Append(Escape(pair.Value)).AppendLine("\");");
            }

            sb.AppendLine();
            sb.Append(indent).AppendLine("    public static readonly DLogTag[] All =");
            sb.Append(indent).AppendLine("    {");
            foreach (var pair in pairs)
            {
                sb.Append(indent).Append("        ").Append(pair.Key).AppendLine(",");
            }

            sb.Append(indent).AppendLine("    };");
            sb.Append(indent).AppendLine("}");

            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>True when the tag name is reserved (currently the DConsole "None"/untagged filter).</summary>
        internal static bool IsReservedTagName(string tag)
        {
            return string.Equals(tag, ReservedNoneTag, StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Converts a tag to a valid C# identifier, or returns <c>null</c> if it is empty/invalid.
        /// Shared with the tags editor so its validation matches what the generator actually emits.
        /// </summary>
        internal static string ToIdentifier(string tag)
        {
            if (string.IsNullOrWhiteSpace(tag))
            {
                return null;
            }

            var sb = new StringBuilder(tag.Length);
            foreach (var ch in tag)
            {
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }

            var id = sb.ToString();
            if (id.Length == 0)
            {
                return null;
            }

            if (char.IsDigit(id[0]))
            {
                id = "_" + id;
            }

            return id;
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
#endif
