// <auto-generated>
//     Generated by DLogTagsGenerator. Do not edit manually.
//     Edit tags in Project Settings > DraasGames, then click "Generate Tags".
// </auto-generated>

using DraasGames.Core.Runtime.Infrastructure.Logger;

namespace DraasGames
{
    public static class DLogTags
    {
        public static readonly DLogTag Gameplay = new DLogTag("Gameplay");
        public static readonly DLogTag UI = new DLogTag("UI");
        public static readonly DLogTag Network = new DLogTag("Network");
        public static readonly DLogTag Audio = new DLogTag("Audio");

        public static readonly DLogTag[] All =
        {
            Gameplay,
            UI,
            Network,
            Audio,
        };
    }
}
